name: Deploy with Ansible

on:
  push:
    branches:
      - maxime

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    environment: production
    steps:

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook install php
        run: |
          ansible-playbook -i server install_mysql.yml

      - name: Run Ansible Playbook install php
        run: |
          ansible-playbook -i server install_php.yml

      - name: Run Ansible Playbook install nginx
        run: |
          ansible-playbook -i server install_nginx.yml

      - name: Run Ansible Playbook install project
        run: |
          ansible-playbook -i server install_project.yml