name: Deploy with Ansible

on:
  push:
    branches:
      - maxime

jobs:
  deploy:
    name: Deploy Ansible Playbook
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python and Install Ansible
      - name: Set up Python and Install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the desired Python version
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Step 3: Execute the Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'