---
- name: Manage MySQL Installation and Configuration
  hosts: server
  become: yes
  vars_files:
    - vars.yml
    - secrets.yml
  tasks:
    - name: Remove MySQL-related directories and files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/mysql
        - /etc/mysql
        - /var/log/mysql

    - name: Install MySQL
      ansible.builtin.apt:
        name: mysql-server
        update_cache: yes
        cache_valid_time: 3600
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Enable configuration
      ansible.builtin.copy:
        src: templates/my.cnf.j2
        dest: /etc/mysql/my.cnf

    - name: Update MySQL root password for all root accounts
      community.mysql.mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ server_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Create a new database
      community.mysql.mysql_db:
        name: app
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"