name: Symfony project

on:
  push:
    branches: [ "maxime" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Set up Python and Install Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i .github/workflows/server.yml .github/workflows/install_php.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i .github/workflows/server.yml .github/workflows/install_mysql.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i .github/workflows/server.yml .github/workflows/install_nginx.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i .github/workflows/server.yml .github/workflows/install_project.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
