mysql_root_password: rootPassword123!
mysql_database: app
mysql_password: rootPassword123!
mysql_user: root
db_port: 3306


project_dest: "/var/www/{{ project_name }}"

server_hostname: private.blizzfull.fr
project_name: ENI-BDE
project_repo: "https://github.com/NorlaXx/ENI-BDE"
db_url: "mysql://root:rootPassword123!@127.0.0.1:3306/{{ mysql_database }}?serverVersion=8.0.32&charset=utf8mb4"